Insure Distortion Keywords Remain in the correct place in the headers
spacetelescope/stwcs pull request #175
Opened 2021-05-05 01:17 UTC by stsci-hack

This set of changes insures that the IDCTAB, NPOLFILE and D2IMFILE keywords remain in the same part of the primary header as the rest of the calibration reference file keywords.  They reported that these keywords were ending up at the end of the primary header after distortion correction by 'updatewcs', so this PR insures that these keywords do not get moved.

2021-05-05 02:23 UTC, stsci-hack commented
CI checks uncovered ways which this PR broke headerlet usage.  Do NOT review until these issues have been resolved, if at all.

2021-05-06 02:45 UTC, mcara requested changes
The `KeyError` in the outer `try-except` block can never occur as `astropy.io.fits.Header.set()` does not (should not) raise exceptions when setting a keyword value since it is equivalent to `dest[key] = source[key]` (neglecting comments). So returned dictionary will always have all `True` values. Moreover, the only place where this function is called does not use the return value at all (which, this return value, does not even make sense) - see https://github.com/spacetelescope/stwcs/blob/d0e856b11e9f1f00f60b59b4124b85ff63f47d18/stwcs/wcsutil/headerlet.py#L2116

I suggest that this function gets simplified to a minimum, with `phdukw` pulled to the top as a constant.

2021-05-06 02:55 UTC, mcara commented
Basically, what I am suggesting is:

```python
# This goes to the top of the file after include statements:
_DIST_KEYWORDS = ['NPOLFILE', 'IDCTAB', 'D2IMFILE', 'SIPNAME', 'DISTNAME']

# the function without docstring [for brevity]:
def update_ref_files(source, dest):
    logger.info("Updating reference files")
    for key in _DIST_KEYWORDS:
        if key in dest:
            dest.set(key, source[key], source.comments[key])
```

That is all that is needed, IMO. If you really need that returned value, then the following would do it:
```python
def update_ref_files(source, dest):
    upd_kwds = {}
    logger.info("Updating reference files")
    for key in _DIST_KEYWORDS:
        if key in dest:
            dest.set(key, source[key], source.comments[key])
            upd_kwds[key] = True
        else:
            upd_kwds[key] = False
    return upd_kwds
```

2021-05-06 13:41 UTC, stsci-hack commented
The functions logic has been simplified as requested in afb7647.  The original function's API was not changed in that commit since this function has been in the public for several years now.

2021-05-06 13:44 UTC, mcara commented
> ... since this function has been in the public for several years now

2021-05-06 13:45 UTC, mcara commented
> ... since this function has been in the public for several years now

I have very serious doubts anyone is ever calling it, at least anyone external.

2021-05-06 13:45 UTC, mcara approved these changes
LGTM

2021-05-06 17:33 UTC, merged